FROM texlive/texlive:latest

# Installation des dépendances nécessaires
RUN apt-get update && apt-get install -y \
    python3-pip \
    pandoc \
    poppler-utils \
    imagemagick \
    python3-venv \


# Install uv (Python package installer)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Add uv to PATH
ENV PATH="/root/.cargo/bin:$PATH"

# Install Python tools using uv
RUN uv tool install black isort
