FROM infocornouaille/tools:base

# Install Python tools using uv
RUN uv tool install latexcor pdfcor panflute jupytercor
# Création des dossiers pour les templates et filtres personnalisés
RUN mkdir -p /usr/share/pandoc/templates \
    /usr/local/share/pandoc/filters \
    /usr/local/share/texmf/tex/latex/local

# Copie des fichiers personnalisés (à adapter selon vos besoins)
COPY pandoc-filters /usr/local/share/pandoc/filters/
COPY pandoc-templates /usr/share/pandoc/templates/
COPY custom-latex /usr/local/share/texmf/tex/latex/local/

# Mise à jour de la base de données de TeXLive
RUN texhash

# Définition du répertoire de travail
WORKDIR /data
